# This is a config for E2B sandbox template.
# You can use template ID (88o7tgyqrl0vof1neyia) or template name (unlovable-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("unlovable-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("unlovable-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('unlovable-nextjs-test-2')

team_id = "90b1cc67-460b-40b6-b753-df0f0482ac6e"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "unlovable-nextjs-test-2"
template_id = "88o7tgyqrl0vof1neyia"
